#define MAX_FILE_NAME_LEN 128

#define SIFT_SUFFIX "sift"

#define DIR_SEPARATOR '/'

#define PREFFIX_SEPARATOR "_"
#define DOT_SEPARATOR "."

#define CAP_WIDTH 640
#define CAP_HEIGHT 480

#define SHOW_PYR_TIMES 1

#define SHOW_MIN_WIDTH 1280
#define SHOW_MIN_HEIGHT 960

#define FRAME_INTERVAL 15
